import { ProductTypes } from "@/types/product";

export const productList: ProductTypes = [
  {
    id: 111,
    kind: "course",
    name: "Học Toeic cấp tốc 550+",
    image: "toeic-550.jpg",
    price: 1500000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
  {
    id: 222,
    kind: "course",
    name: "100 Days of Code: The Complete Python Pro BootcampMaster Python by building 100 projects in 100 days.",
    image: "toeic-750.jpg",
    price: 399000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
  {
    id: 333,
    kind: "course",
    name: "Học Toeic cấp tốc 550+",
    image: "toeic-550.jpg",
    price: 1500000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
  {
    id: 444,
    kind: "course",
    name: "100 Days of Code: The Complete Python Pro BootcampMaster Python by building 100 projects in 100 days.",
    image: "toeic.jpg",
    price: 399000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
  {
    id: 555,
    kind: "course",
    name: "Học Toeic cấp tốc 550+",
    image: "toeic-550.jpg",
    price: 1500000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
  {
    id: 666,
    kind: "course",
    name: "100 Days of Code: The Complete Python Pro BootcampMaster Python by building 100 projects in 100 days.",
    image: "toeic-750.jpg",
    price: 399000,
    des: "Learn data science, automation, build websites, games and apps!",
    liked: false,
  },
];
